// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0OVz-0hUIIoX7zf7jBzntk5CkKApUUwQ',
    appId: '1:744862238311:web:09540bdfa3435033ce76c2',
    messagingSenderId: '744862238311',
    projectId: 'ev-manager-app',
    authDomain: 'ev-manager-app.firebaseapp.com',
    storageBucket: 'ev-manager-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsuVVAHq_eGI3gdMVoZ4lSR6cd9F2dijU',
    appId: '1:744862238311:android:feb300105490a91ace76c2',
    messagingSenderId: '744862238311',
    projectId: 'ev-manager-app',
    storageBucket: 'ev-manager-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdyfTJvl1iKQzmt1IeV36cLOJEyrQD17A',
    appId: '1:744862238311:ios:e4ea37304beffcccce76c2',
    messagingSenderId: '744862238311',
    projectId: 'ev-manager-app',
    storageBucket: 'ev-manager-app.firebasestorage.app',
    iosBundleId: 'com.example.evManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0OVz-0hUIIoX7zf7jBzntk5CkKApUUwQ',
    appId: '1:744862238311:web:a4e02e8902df374dce76c2',
    messagingSenderId: '744862238311',
    projectId: 'ev-manager-app',
    authDomain: 'ev-manager-app.firebaseapp.com',
    storageBucket: 'ev-manager-app.firebasestorage.app',
  );
}
